import './globals.css';
import Providers from './providers';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ScrollToHash from '@/components/ScrollToHash';
import { Suspense } from 'react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Inter, Bebas_Neue, IBM_Plex_Mono } from 'next/font/google';
import IntroOverlay from '@/components/IntroOverlay';
import { ORG_ID, organizationNode, webSiteNode } from '@/utils/schema';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-suisseintl',
  weight: ['400', '500'],
});

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-suisseintlcond',
  weight: ['400'],
});

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-suisseintlmono',
  weight: ['400'],
});

export const metadata = {
  metadataBase: new URL('https://www.docshift.tech'),
  title: {
    default: 'Free PDF Tools Online – Merge, Compress, Convert | DocShift',
    template: '%s | DocShift',
  },
  description: 'Free online PDF tools that work entirely in your browser. Merge, compress, convert PDF to Word, split and edit PDFs instantly. No uploads, 100% private.',
  keywords: 'pdf tools, merge pdf without uploading, compress pdf in browser, completely free pdf tools online',
  authors: [{ name: 'DocShift' }],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  openGraph: {
    type: 'website',
    url: 'https://www.docshift.tech/',
    title: 'Free PDF Tools Online – Merge, Compress, Convert | DocShift',
    description: 'Free online PDF tools that work entirely in your browser. Merge, compress, convert PDF to Word, split and edit PDFs instantly. No uploads, 100% private.',
    siteName: 'DocShift',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Free PDF Tools Online – Merge, Compress, Convert | DocShift',
    description: 'Free online PDF tools that work entirely in your browser. Merge, compress, convert PDF to Word, split and edit PDFs instantly. No uploads, 100% private.',
    site: '@soumyachk1',
  },
  icons: {
    icon: '/favicon.svg',
    // Points at the PNG generated by app/apple-icon.tsx — iOS does not support
    // SVG in this slot. Declared explicitly rather than left to the file
    // convention: setting `metadata.icons` at all suppresses convention-derived
    // icon tags, so an omitted `apple` key emits no apple-touch-icon at all.
    apple: [{ url: '/apple-icon', sizes: '180x180', type: 'image/png' }],
  },
  manifest: '/manifest.json',
};

export const viewport = {
  themeColor: '#e5e7eb',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({ children }) {
  const softwareSchema = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'DocShift PDF Tools',
    url: 'https://www.docshift.tech',
    applicationCategory: 'UtilitiesApplication',
    operatingSystem: 'Web Browser',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description: 'Free browser-based PDF tools. Merge, compress, convert and edit PDFs with 100% privacy.',
    author: { '@id': ORG_ID },
  };

  return (
    <html lang="en" className={`${inter.variable} ${bebasNeue.variable} ${ibmPlexMono.variable}`} suppressHydrationWarning>
      <head>
        <link rel="alternate" type="text/plain" href="https://www.docshift.tech/llms.txt" title="LLM-readable site summary" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webSiteNode) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationNode) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }} />
      </head>
      <body>
        <IntroOverlay />
        <SpeedInsights />
        <Providers>
          <Suspense>
            <ScrollToHash />
          </Suspense>
          <Navbar />
          <main className="pt-20 sm:pt-24 min-h-screen">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
