import {
  Archive,
  Combine,
  Crop,
  Droplets,
  EyeOff,
  FileOutput,
  FileText,
  FolderOpen,
  GitCompare,
  Globe,
  Hash,
  Image,
  Images,
  Languages,
  LayoutGrid,
  Lock,
  Minimize2,
  MonitorPlay,
  Pen,
  PenLine,
  Presentation,
  RotateCw,
  ScanLine,
  ScanText,
  Scissors,
  Sheet,
  Table,
  Trash2,
  Unlock,
  Wrench,
  Zap,
  ShieldCheck,
  ServerCrash,
  HeartHandshake,
  Search,
  X,
  Menu,
  ChevronDown,
  ArrowUpRight,
  Gift,
  MonitorSmartphone,
  PenLine as PenLineIcon,
  RotateCw as RotateCwIcon,
  Hash as HashIcon,
  Droplets as DropletsIcon,
  Crop as CropIcon,
  PenLine as PenIcon,
  Unlock as UnlockIcon,
  Lock as LockIcon,
  Pen as PenIconAlt,
  EyeOff as EyeOffIcon,
  GitCompare as GitCompareIcon,
  Languages as LanguagesIcon,
} from 'lucide-react';

const IconsMap = {
  Archive,
  Combine,
  Crop,
  Droplets,
  EyeOff,
  FileOutput,
  FileText,
  FolderOpen,
  GitCompare,
  Globe,
  Hash,
  Image,
  Images,
  Languages,
  LayoutGrid,
  Lock,
  Minimize2,
  MonitorPlay,
  Pen,
  PenLine,
  Presentation,
  RotateCw,
  ScanLine,
  ScanText,
  Scissors,
  Sheet,
  Table,
  Trash2,
  Unlock,
  Wrench,
  Zap,
  ShieldCheck,
  ServerCrash,
  HeartHandshake,
  Search,
  X,
  Menu,
  ChevronDown,
  ArrowUpRight,
  Gift,
  MonitorSmartphone,
};

/**
 * Get icon component by name
 * @param {string} name - Icon name from tools.js
 * @returns {React.ComponentType} Icon component or FileText fallback
 */
export function getIcon(name) {
  return IconsMap[name] || FileText;
}

// Re-export for components that need full access
export { IconsMap as Icons };
